[package]
name = "rustytk"
version = "0.1.0"
authors = ["Andrei Nagacevschi <andrein_bio@yahoo.com>"]
edition = "2018"

[lib]
name = "rustytk"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.22"
gfx-hal = "0.5"
glsl-to-spirv = "0.1.7"

[build-dependencies]
glsl-to-spirv = "0.1.7"

[target.'cfg(target_os = "macos")'.dependencies.backend]
package = "gfx-backend-metal"
version = "0.5"

[target.'cfg(windows)'.dependencies.backend]
package = "gfx-backend-dx12"
version = "0.5"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies.backend]
package = "gfx-backend-vulkan"
version = "0.5"
